# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dhruv/repos/hsvgen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dhruv/repos/hsvgen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dhruv/repos/hsvgen/CMakeFiles /home/dhruv/repos/hsvgen/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dhruv/repos/hsvgen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hsvgen

# Build rule for target.
hsvgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hsvgen
.PHONY : hsvgen

# fast build rule for target.
hsvgen/fast:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/build
.PHONY : hsvgen/fast

buildTree.o: buildTree.cpp.o
.PHONY : buildTree.o

# target to build an object file
buildTree.cpp.o:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/buildTree.cpp.o
.PHONY : buildTree.cpp.o

buildTree.i: buildTree.cpp.i
.PHONY : buildTree.i

# target to preprocess a source file
buildTree.cpp.i:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/buildTree.cpp.i
.PHONY : buildTree.cpp.i

buildTree.s: buildTree.cpp.s
.PHONY : buildTree.s

# target to generate assembly for a file
buildTree.cpp.s:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/buildTree.cpp.s
.PHONY : buildTree.cpp.s

hsvgen.o: hsvgen.cpp.o
.PHONY : hsvgen.o

# target to build an object file
hsvgen.cpp.o:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/hsvgen.cpp.o
.PHONY : hsvgen.cpp.o

hsvgen.i: hsvgen.cpp.i
.PHONY : hsvgen.i

# target to preprocess a source file
hsvgen.cpp.i:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/hsvgen.cpp.i
.PHONY : hsvgen.cpp.i

hsvgen.s: hsvgen.cpp.s
.PHONY : hsvgen.s

# target to generate assembly for a file
hsvgen.cpp.s:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/hsvgen.cpp.s
.PHONY : hsvgen.cpp.s

preprocess.o: preprocess.cpp.o
.PHONY : preprocess.o

# target to build an object file
preprocess.cpp.o:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/preprocess.cpp.o
.PHONY : preprocess.cpp.o

preprocess.i: preprocess.cpp.i
.PHONY : preprocess.i

# target to preprocess a source file
preprocess.cpp.i:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/preprocess.cpp.i
.PHONY : preprocess.cpp.i

preprocess.s: preprocess.cpp.s
.PHONY : preprocess.s

# target to generate assembly for a file
preprocess.cpp.s:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/preprocess.cpp.s
.PHONY : preprocess.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... hsvgen"
	@echo "... rebuild_cache"
	@echo "... buildTree.o"
	@echo "... buildTree.i"
	@echo "... buildTree.s"
	@echo "... hsvgen.o"
	@echo "... hsvgen.i"
	@echo "... hsvgen.s"
	@echo "... preprocess.o"
	@echo "... preprocess.i"
	@echo "... preprocess.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

