# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dhruv/repos/hsvgen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dhruv/repos/hsvgen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dhruv/repos/hsvgen/CMakeFiles /home/dhruv/repos/hsvgen/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dhruv/repos/hsvgen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hsvgen

# Build rule for target.
hsvgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hsvgen
.PHONY : hsvgen

# fast build rule for target.
hsvgen/fast:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/build
.PHONY : hsvgen/fast

src/buildTree.o: src/buildTree.cpp.o
.PHONY : src/buildTree.o

# target to build an object file
src/buildTree.cpp.o:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/src/buildTree.cpp.o
.PHONY : src/buildTree.cpp.o

src/buildTree.i: src/buildTree.cpp.i
.PHONY : src/buildTree.i

# target to preprocess a source file
src/buildTree.cpp.i:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/src/buildTree.cpp.i
.PHONY : src/buildTree.cpp.i

src/buildTree.s: src/buildTree.cpp.s
.PHONY : src/buildTree.s

# target to generate assembly for a file
src/buildTree.cpp.s:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/src/buildTree.cpp.s
.PHONY : src/buildTree.cpp.s

src/hsvgen.o: src/hsvgen.cpp.o
.PHONY : src/hsvgen.o

# target to build an object file
src/hsvgen.cpp.o:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/src/hsvgen.cpp.o
.PHONY : src/hsvgen.cpp.o

src/hsvgen.i: src/hsvgen.cpp.i
.PHONY : src/hsvgen.i

# target to preprocess a source file
src/hsvgen.cpp.i:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/src/hsvgen.cpp.i
.PHONY : src/hsvgen.cpp.i

src/hsvgen.s: src/hsvgen.cpp.s
.PHONY : src/hsvgen.s

# target to generate assembly for a file
src/hsvgen.cpp.s:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/src/hsvgen.cpp.s
.PHONY : src/hsvgen.cpp.s

src/preprocess.o: src/preprocess.cpp.o
.PHONY : src/preprocess.o

# target to build an object file
src/preprocess.cpp.o:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/src/preprocess.cpp.o
.PHONY : src/preprocess.cpp.o

src/preprocess.i: src/preprocess.cpp.i
.PHONY : src/preprocess.i

# target to preprocess a source file
src/preprocess.cpp.i:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/src/preprocess.cpp.i
.PHONY : src/preprocess.cpp.i

src/preprocess.s: src/preprocess.cpp.s
.PHONY : src/preprocess.s

# target to generate assembly for a file
src/preprocess.cpp.s:
	$(MAKE) -f CMakeFiles/hsvgen.dir/build.make CMakeFiles/hsvgen.dir/src/preprocess.cpp.s
.PHONY : src/preprocess.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... hsvgen"
	@echo "... rebuild_cache"
	@echo "... src/buildTree.o"
	@echo "... src/buildTree.i"
	@echo "... src/buildTree.s"
	@echo "... src/hsvgen.o"
	@echo "... src/hsvgen.i"
	@echo "... src/hsvgen.s"
	@echo "... src/preprocess.o"
	@echo "... src/preprocess.i"
	@echo "... src/preprocess.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

